# Build stage
FROM rust:slim AS build
WORKDIR /app
COPY . .
RUN cargo build --release

# Runtime stage
FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y libssl3 ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY --from=build /app/target/release/{{ project_name }} .
EXPOSE 8080
CMD ["./{{ project_name }}"]
