use anyhow::Result;
use harn_core::context::{ProjectContext, WriteStatus};
use harn_core::module::{Module, ModuleId};
use harn_templates::TemplateEngine;

/// Git configuration module.
///
/// Generates .gitignore (language-aware) and .gitattributes.
pub struct GitModule;

impl Module for GitModule {
    fn id(&self) -> ModuleId {
        "git"
    }

    fn name(&self) -> &str {
        "Git Configuration"
    }

    fn description(&self) -> &str {
        ".gitignore, .gitattributes"
    }

    fn generate(&self, ctx: &mut ProjectContext) -> Result<Vec<(String, WriteStatus)>> {
        let engine = TemplateEngine::from_context(ctx);
        let vars = TemplateEngine::vars_from_context(ctx);
        let force = ctx.force;
        let mut files = Vec::new();

        let git_config = ctx.config.modules.git.clone().unwrap_or_default();

        if git_config.gitignore {
            // Build composite .gitignore from language-specific fragments
            let mut content = String::new();
            content.push_str("# Generated by harn\n\n");

            // Common ignores
            content.push_str("# Environment\n.env\n.env.local\n.env.*.local\n\n");
            content.push_str("# IDE\n.idea/\n*.swp\n*.swo\n*~\n\n");
            content.push_str("# OS\n.DS_Store\nThumbs.db\n\n");

            for lang in &ctx.config.stacks.languages {
                match lang.as_str() {
                    "rust" => {
                        content.push_str("# Rust\ntarget/\n\n");
                    }
                    "go" => {
                        content.push_str("# Go\nbin/\ncoverage.out\ntmp/\n\n");
                    }
                    "typescript" | "javascript" => {
                        content.push_str(
                            "# Node\nnode_modules/\ndist/\nbuild/\n.cache/\ncoverage/\n\n",
                        );
                    }
                    "dart" | "flutter" => {
                        content.push_str("# Flutter/Dart\n.dart_tool/\nbuild/\n.flutter-plugins\n.flutter-plugins-dependencies\n*.g.dart\n*.freezed.dart\n\n");
                    }
                    "python" => {
                        content.push_str(
                            "# Python\n__pycache__/\n*.pyc\n.venv/\nvenv/\n*.egg-info/\ndist/\n\n",
                        );
                    }
                    "java" => {
                        content
                            .push_str("# Java\nbuild/\n.gradle/\n*.class\n*.jar\n*.war\nout/\n\n");
                    }
                    "cpp" | "c" => {
                        content.push_str("# C/C++\nbuild/\ncmake-build-*/\n*.o\n*.a\n*.so\n*.dylib\n*.exe\ncompile_commands.json\n\n");
                    }
                    _ => {}
                }
            }

            content.push_str("# Logs\n*.log\nlogs/\n\n");
            content.push_str("# Temp\ntmp/\n.tmp/\n\n");
            content.push_str("# Claude Code worktrees\n.claude/worktrees/\n\n");
            content.push_str("# Harn backups\n.harn-backup/\n");

            let dst = ctx.path(".gitignore");
            let status = ctx.write_file(&dst, &content)?;
            files.push((".gitignore".into(), status));
        }

        if git_config.gitattributes {
            let dst = ctx.path(".gitattributes");
            if engine.has_template("git/gitattributes") {
                let status = engine.render_to("git/gitattributes", &vars, &dst, force)?;
                files.push((".gitattributes".into(), status));
            }
        }

        Ok(files)
    }
}
